### ISSUE TITLE
Validador de Telefone

### ISSUE THREAD

**Issue by halysongoncalves** [concretesolutions/canarinho#15]
Atualmente o validador de telefone contempla números com 9 dígito?
Estou utilizando o validador de telefone, entretanto, mesmo o número estando parcialmente incompleto, o callback de ehValido é chamado.

Segue o trecho de código:

`appCompatEditTextPhoneSecondary.addTextChangedListener(new MascaraNumericaTextWatcher.Builder()
                .paraMascara("(##) #####-####")
                .build())`

Para teste, utilize esse número de exemplo: 21980777957

@cs-victor-nascimento

**Comment by cs-victor-nascimento** [comment]
Nesse exemplo você não está usando nenhum validador. O builder aceita um validador customizado no método `comValidador(Validador val)`. Existe um watcher pronto para telefone [aqui](https://github.com/concretesolutions/canarinho/blob/master/canarinho/src/main/java/br/com/concretesolutions/canarinho/watcher/TelefoneTextWatcher.java).

O validador, no entanto, não está fazendo muitas validações. Ele apenas limita em DDD masi oito ou nove dígitos. Não sei se podemos ser mais agressivos com a validação e garantir que todos os números que começam com 9 terão 9 dígitos.

**Comment by cs-victor-nascimento** [comment]
Vou fechar este issue. Caso queira discutir mais o assunto, por favor, sinta-se a vontade para reabrí-lo.
