### ISSUE TITLE
Manter simbolo Real e somente teclado numérico

### ISSUE THREAD

**Issue by alesanfer** [concretesolutions/canarinho#19]
Quando seto na view como o exemplo: 

<android.support.design.widget.TextInputEditText
    android:id="@+id/amount"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:hint="@string/hint_value"
    android:inputType="textFilter|number"
    android:maxLength="13"
    android:text="0,00" />

se manter somente android:inputType="textFilter|number" o simbolo de Real não é visível. 

O simbolo somente é visivel se  remover o inputType "number" e colocar "text"  da seguinte forma: 

android:inputType="textFilter|text"

Gostaria de manter o simbolo de Real mas com teclado somente numérico, é possível? 

Obrigado

**Comment by cs-victor-nascimento** [comment]
Tem um PR aberto para isso que estamos somente aguardando um rebase na master para corrigir. Deve sair uma versão logo com esta feature.

Qualquer siga o #17

**Comment by cs-victor-nascimento** [comment]
PR foi mergeado. 

Faremos um release.
