### ISSUE TITLE
Múltiplas máscaras 

### ISSUE THREAD

**Issue by pedrofsn** [concretesolutions/canarinho#22]
A lib consegue suportar múltiplas máscaras para um mesmo EditText e ir se adequando a mais provável de acordo com o dado inserido? Ou seja, determinar qual deve ser aplicada dentre as máscaras de um conjunto, ex.:  Sem o nono dígito "(##) ####-####" e com o nono dígito "(##) # ####-####"

**Comment by cs-victor-nascimento** [comment]
A máscara de telefone não tem essa formatação mas pode ser um exemplo de implementação customizada.

Podemos pensar em dar opções do formatador de telefone padrão. Vou criar um issue específico para isso.

Em todo caso, por enquanto não temos essa configuração.
