### ISSUE TITLE
Não é possivel baixar a Dependencia 

### ISSUE THREAD

**Issue by JDSCaram** [concretesolutions/canarinho#27]
E ai pessoal, estou tentando utilizar a lib, ao add ao projeto,
Após sincronização do gradle, estou tomando o seguinte erro:

`Error:(128, 20) Failed to resolve: br.com.concrete:canarinho:2.0.0`

Ha um exemplo de configuração utilizando a dependencia?
`implementation 'br.com.concrete:canarinho:2.0.0'`

**Comment by cs-rafael-toledo** [comment]
Olá @JDSCaram! Estamos com um pequeno problema no Bintray, por isso a publicação não foi concluída. Mas já estamos corrigindo, então logo vai estar publicada.

**Comment by cs-victor-nascimento** [comment]
Release 2.0.0 já está no bintray e agora estamos esperando a aprovação para subir no Maven Central (para que você não necessite incluir repositórios customizados na sua configuração).

O prazo agora é variável. Se tiver urgência de uso, recomento as versões antigas:

```gradle
implementation 'br.com.concretesolutions:canarinho:1.2.0'
```

Repare que alteramos o pacote!!! Isso porque a empresa mudou de nome :) a versão 2.0 é major justamente por causa disso.

Vou deixar o issue aberto até subir em Maven Central.

**Comment by cs-victor-nascimento** [comment]
Já está no bintray a versão 2.0.0 que mudou de pacote.

Agora é `br.com.concrete:canarinho:2.0.0`.

Valeu!
