### ISSUE TITLE
FORMATADOR_MOEDA falha com um NPE na API 28

### ISSUE THREAD

**Issue by rafaeltoledo** [concretesolutions/canarinho#38]
**Describe the bug**
Na API 28, o `FORMATADOR_MOEDA` falha com um NPE, aparentemente devido a alguma mudança de comportamento não desejada na implementação de `NumberFormat`.

**To Reproduce**
```java
// Executando no Android P
final String value = "1.000.000,00";
assertEquals("1000000.00", Formatador.VALOR.desformata(value));
```

**Additional context**
[Bug aberto no issue tracker do Android](https://issuetracker.google.com/u/1/issues/120240617)

**Comment by mcassiano** [comment]
@cs-bruno-silva ping!
