### ISSUE TITLE
Lib com plugin java somente

### ISSUE THREAD

**Issue by GabriellCosta** [concretesolutions/canarinho#43]
Seria interessante quebrar a lib em duas uma somente com os formatadores e verificadores e afins que não precisem depender do android em si, e outra com as funcionalidades usadas no android em si onde ela depende desta outra primeira lib

Lib Android <-------Lib Java

Desta maneira a mesma poderia ser usada no próprio backend alguém precise de alguma validação ou formatar algo

**Comment by Megamiun** [comment]
Concordo, fui ver em nosso projeto backend e temos um caso de uma CPFUtils não muito agradável.

Ai eu pensei: e se usassemos a lib da Concrete destinada a isso?

Porém ao ver, olhei que ela estava acoplada ao android e que por isso não poderia utilizar uma lógica universal dela. Adoraria que fizessem isso.

**Comment by rafaeltoledo** [comment]
Fora do Android, tecnicamente já temos a [Stella](https://github.com/caelum/caelum-stella), mantida pela Caelum.

**Comment by cs-bruno-silva** [comment]
Nesse caso acredito que faz mais sentido utilizar a Stella.
https://github.com/caelum/caelum-stella/wiki/Validadores-core

**Comment by cs-bruno-silva** [comment]
Talvez usar o Stella aqui e só fazer uma ponte entre os formatadores e TextWatchers.
