### ISSUE TITLE
É realmente necessário  ter um validador e um evento de validação na mascara numérica?

### ISSUE THREAD

**Issue by davirodrigues07** [concretesolutions/canarinho#8]
Olhando o código e testando em uma aplicação que criei, percebi que sempre que se usa uma mascara numérica faz-se necessário um **Validador** e um **EventoDeValidacao**. Mas algumas vezes a mascara numérica já supre a necessidade ou não é possível fazer uma validação (como por exemplo em uma mascara de campo para identidade, já que a estrutura de identidade pode ser diferente em diferentes estados do Brasil). Então queria questionar a [obrigatoriedade](https://github.com/concretesolutions/canarinho/blob/master/canarinho/src/main/java/br/com/concretesolutions/canarinho/watcher/MascaraNumericaTextWatcher.java#L108) de usar um [Validador](https://github.com/concretesolutions/canarinho/blob/master/canarinho/src/main/java/br/com/concretesolutions/canarinho/validator/Validador.java) e um [EventoDeValidacao](https://github.com/concretesolutions/canarinho/blob/master/canarinho/src/main/java/br/com/concretesolutions/canarinho/watcher/evento/EventoDeValidacao.java).

**Comment by cs-victor-nascimento** [comment]
Não é obrigatório não. Só está assim pois era um requisito local na hora que foi criado.

Aceitamos Pull Requests :dart: :)

**Comment by davirodrigues07** [comment]
Vou baixar o projeto e tentar ajudar no que eu puder :)
